[package]
name = "watchful-infinitime-recovery"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
embedded-hal-async = "1.0.0"
embedded-io = "0.6.0"
embedded-storage = "0.3.1"
embedded-hal = "1.0.0"

[dev-dependencies]
futures-test = "0.3"
